version: "3.8"

services:
    node:
        build:
            context: .
            dockerfile: Dockerfile
            args:
                NODE_ENV: production
        working_dir: /app
        ports:
            - "9511:3000"
        restart: unless-stopped